# Generated by Django 5.0.4 on 2024-04-24 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0003_company_idno_alter_company_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='year_founded',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
